### ISSUE TITLE
Issue with the compressed Javascript href to foundation.min.js

### ISSUE THREAD

**Issue by adithsyam** [cagomezr/WebNote#3]
I was going through your code, and I found this issue with foundation.min.js file. I noticed that it has a function type error with foundation.core.js. Basically to fix this issue would be to fix the issue in the foundation.js file but removing the href from the code would fix this error from and would still run your code just fine.

**Comment by cagomezr** [comment]
Thanks for the pull request this has been solved with pull request by you on #4  thank you once again
