### ISSUE TITLE
Issue Regarding Text Area

### ISSUE THREAD

**Issue by Manan311** [cagomezr/WebNote#5]
Hello Cagomezr,

I have an issue regarding the text area. When I opened your link I couldn't tell will I have to type my notes. So I would like to resolve this problem for you with a border around your text area if thats fine and a placeholder to your div so the users know where they can type without clicking on the screen multiple times before starting.

Thank You,
Manan Patel

**Comment by cagomezr** [comment]
thanks for the fix, please however  ask for the  pull before  closing issue for better issue  track , thank you. Fixed in Pull #6
